### ISSUE TITLE
Error: Unexpected server response: 401

### ISSUE THREAD

**Issue by huwenkai26** [ting-xing/spark-desk#1]
命令行执行报错 401

**Comment by ting-xing** [comment]
感谢你的反馈。
因为创建的默认文件使用星火大模型V2的版本，这个版本并未适配成功。
![image](https://github.com/1517607397/spark-desk/assets/45745414/3af321fe-e2ae-4cc9-9003-91fa97e61d06)

你可以通过手动调整配置文件，在当前用户目录下的 .spark-desk 文件中，设置 version 的版本为 1。

你可以通过删除配置文件，重新安装 1.0.5 版本后重试。
https://www.npmjs.com/package/spark-desk/v/1.0.5
