### ISSUE TITLE
星火3.0可以支持下吗

### ISSUE THREAD

**Issue by huwenkai26** [ting-xing/spark-desk#2]

**Comment by ting-xing** [comment]
嗯，我了解一下，尽快支持。

**Comment by huwenkai26** [comment]
你可以将url 设置成初始化传入的一个参数

**Comment by ting-xing** [comment]
已支持3.0接口，可通过version参数改变使用版本，达到切换url的目的。
全局安装 `npm i spark-desk@1.2.0 -g`
项目里安装 `npm i spark-desk@1.2.0 -S`
如果之前已经全安居安装过，3.0的配置信息可能不一样，注意修改 `.spark-desk` 配置文件。
